### ISSUE TITLE
Any plans for adding more functionality?

### ISSUE THREAD

**Issue by irumiha** [carlosedp/scala3-quarkus-quickstart#10]
Hey, interesting work here. Are there any plans to expand the example with database persistence, or some other integrations, like Kafka?

Thanks.

**Comment by carlosedp** [comment]
Added a Kafka sample app with a producer/consumer/processor components in the last commits.

I'd love to hear some feedback.

**Comment by irumiha** [comment]
I'm surprised how little was necessary to make it work. 

To contribute a little I created a PR #13 which adds two persistence examples. One is Java-centric with Hibernate and another is using the new Scala 3 Magnum library.

**Comment by irumiha** [comment]
I agree, this is all very simple, no need for multiple repos. Maybe add some comments in pom.xml to remove dependencies if they are not needed. For example remove the hibernate dependency if a developer will use Magnum.
