### ISSUE TITLE
Add test cases and simple UI for persistence samples

### ISSUE THREAD

**Issue by carlosedp** [carlosedp/scala3-quarkus-quickstart#15]
Could you help-out @irumiha ?

Maybe a simple HTML for user input/get for interaction.

**Comment by irumiha** [comment]
Sure, I'll whip up something and open a PR.

**Comment by carlosedp** [comment]
Played a bit and added a Magnum UI and a Delete endpoint in e2179908701ec3d07eaadb394b33bb67fdc257e0..9c5eb37df7a0e8d73f13cf4c284db4d0eb0263f3

**Comment by irumiha** [comment]
Heh I also did some work: #17

**Comment by carlosedp** [comment]
Closed by #17.
Thanks @irumiha!
